POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Produto 2",
  "price": 10.02
}

###
GET http://localhost:3000/products

###
GET http://localhost:3000/products/1

### Atualização - Update
# Put tem atualização completa, Patch tem atualização parcial
PATCH http://localhost:3000/products/1
Content-Type: application/json

{
  "name": "Produto 1 alterado",
  "price": 10.03
}

###
DELETE http://localhost:3000/products/2
